
// Search Trails
export const GET_TRAILS = 'GET_TRAILS'
export const GET_TRAILS_PENDING = 'GET_TRAILS_PENDING'
export const GET_TRAILS_REJECTED = 'GET_TRAILS_REJECTED'
export const GET_TRAILS_FULFILLED = 'GET_TRAILS_FULFILLED'
